grammar.js
src/grammar.json
src/parser.c
test/corpus/select.txt

Fix bug in string literals

---

.gitignore
Package.swift
bindings/swift/TreeSitterSQL/sql.h

This adds Swift bindings and Swift Package Manager (SPM) support. Parser is unchanged.
I've been going through and trying to add Swift bindings for a bunch of parsers. Would be happy to answer questions!

SPM support

---

.github/workflows/ci.yml

Addressing @kristijanhusak suggestion in #47 to run CI on pull requests.

Run tests on pull requests

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/select.txt

This simply adds the ability to nest joins.

Allow for nested joins

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/drop.txt

Add `drop index` statement

---

grammar.js
test/corpus/create.txt

- Add options to views
- Creation of views using shortcut column specification
- `as select` in optional parens

feat: add more options to pg views

---

grammar.js
test/corpus/create.txt

adds support for the MySQL ENUM type: https://dev.mysql.com/doc/refman/8.0/en/enum.html

add support for mysql enum type

---

grammar.js
test/corpus/select.txt

fix: case when with between statement

---

grammar.js
test/corpus/alter.txt

Closes #151
Remark: need to add new keywords `tables`, `wait` and `nowait` to the highlights after merging.

feat: add mysql rename statement

---

.github/workflows/ci.yml

Add ci check step to check for `ERROR` in tests, excluding errors.txt

ci: check tests for `ERROR`

---

package.json
queries/highlights.scm
test/highlight/query.sql

See https://github.com/nvim-treesitter/nvim-treesitter/pull/4979
Add new highlight tests to make integration with editors easier. The `highlights.scm` file can be copied as is to `nvim-treesitter`

feat(tests): Add highlight tests

---

grammar.js
queries/highlights.scm
test/corpus/functions.txt
test/corpus/group_by.txt
test/corpus/select.txt
test/corpus/window_functions.txt

Add `_aggregate_function` as part of `invocation`.
Closes #158 and supersedes #159

refactor: `group_concat` and `_aggregate_function` to `invocation`

---

grammar.js
test/corpus/select.txt

I think this conflict declaration for `between` is all we need!

feat: support NOT IN

---

.github/workflows/gh-pages.yml

The files contained inside the queries folder are needed for this to work with SPM.

Update action to copy queries folder

---

src/scanner.c

fixes #221 
I think I have found the issue, but I suspect that there are more since we are missing a lot of bounds checks in the `scanner.c`.
We should also avoid `strcpy` in favour of `strncpy` or even better `memcpy`. But I am by no means an expert in C.
Steps to reproduce:
(I use `tree-sitter-cli` from crates.io)
1. Setup the tree-sitter-cli config in `~/.config/tree-sitter/config.json` and specify the parser-directories. This should point to this repo.
2. run `tree-sitter generate` to create the `parser.c`
3. compile with `cc -shared -O -D_FORTIFY_SOURCE=3 -fPIE -fPIC -I./src src/parser.c src/scanner.c -o sql.so`
4. run `valgrind tree-sitter parse <statements.sql>`
The examples from issue #221 reveal that in line 185 (almost at the end) there was a `malloc` with `length - 1`
Valgrind …

fix: segfault in scanner.c

---

.github/workflows/ci.yml
.github/workflows/gh-pages.yml
.github/workflows/npm-publish.yml
CHANGELOG.md
package-lock.json
package.json

Merging the release commit into the main branch cc @matthias-Q

chore(release): 0.1.1

---

.github/workflows/gh-pages.yml

The last argument is the destination so I moved cargo.toml to before the target directory.

fix: Update gh-pages.yml

---

CHANGELOG.md
Cargo.toml
package.json
pyproject.toml

ran `npm run release` + updated the versions manually in Cargo.toml + pyproject.toml

chore(release): 0.3.2

---

CHANGELOG.md
Cargo.toml
bindings/rust/build.rs
package.json
pyproject.toml

The latest release doesn't include the binding code to build the scanner.
see: https://github.com/DerekStride/tree-sitter-sql/pull/265#issuecomment-2254336472
@HerringtonDarkholme @alexbit-codemod

Make sure to build scanner

---

CHANGELOG.md
Cargo.toml
package.json
pyproject.toml

Prepare new release to trigger pypi workflow, closes #270

chore(release): 0.3.4

---

CHANGELOG.md
Cargo.toml
package.json
pyproject.toml

Cut a new version to reattempt the publishing of the lastest packages.

chore(release): 0.3.5

---

package.json

Add correct script in package.json again. Should fix failing gh_release action

fix: package json scripts

---

CHANGELOG.md
package.json

Bump to next version, replacement of #291

chore(release): 0.3.6

---

CHANGELOG.md
CMakeLists.txt
Cargo.toml
package.json
pyproject.toml
tree-sitter.json

There were a few errors with publishing 0.3.6 so I'm bumping everything to 0.3.7.

chore(release): 0.3.7

---

src/scanner.c

Fixes #268. See https://github.com/DerekStride/tree-sitter-sql/issues/268#issuecomment-2691384571 for more info.

fix: incorrect function signature in external scanner

---

grammar.js
test/corpus/functions.txt

Closes #325
This adds special syntax for mysql's extract function. This is not very generic and there may be a better way.

feat: parse mysql extract function
