DerekStride/tree-sitter-sql

- grammar.js
- src/grammar.json
- src/node-types.json
- src/parser.c
- test/corpus/select.txt
This PR tackles 2 separate issues:
1. `DISTINCT` wasn't really a function and I had implemented as if it was a function. We now properly support the keyword `DISTINCT`.
2. Some functions, can only have 1 parameter so I split functions into 2 types: unary and multi-parameter functions. This can be further split if needed in the future.
> Better Function implementation

- grammar.js
- test/corpus/functions.txt
- test/corpus/select.txt
also involved a little precedence tweaking for parametric types (reasonable) and fields (kind of odd)
> Postgres array[1, 2, 3] literals

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/group_by.txt
- test/corpus/select.txt
I added a commit with some small refactors, mostly moving tests for group by to it's own file and adding an extra test case for COUNT in the HAVING clause.
The second commit adds support for `IGNORE INDEX`, there was no keyword for ignore either.
> Ignore Index

- grammar.js
- src/grammar.json
- test/corpus/select.txt
I fixed the precedence for predicates connected with `OR` e.g. disjunctive predicates.
I also fixed the handling of nested unary predicates e.g.
```sql
is_not_deleted AND is_published
```
```scheme
(predicate
left: (predicate
operand: (field name: (identifier)))
operator: (keyword_and)
right: (predicate
operand: (field name: (identifier))))
```
Previously it was
```scheme
(predicate
left: (field name: (identifier))
operator: (keyword_and)
right: (field name: (identifier)))
```
> Disjunctive fixes & Unary Predicate enhancements

- README.md
- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/delete.txt
- test/corpus/expressions.txt
- test/corpus/functions.txt
- test/corpus/group_by.txt
- test/corpus/index.txt
- test/corpus/select.txt
- test/corpus/subquery.txt
- test/corpus/update.txt
- test/corpus/window_functions.txt
Alternative to #62
The goal of this grammar is to be permissive and be able to parse and make sense of many different SQL dialects. Given this goal we have don't have a clear canonical reference implementation to base our grammar on. There are many conflicting implementations and in the past I haven't compared them in-depth. Without a clear reference and conflicting implementations it leaves us free to choose the best structure for our needs.
> redundancy between our predicate and binary_expression. Really a predicate is a binary (or unary!) expression that resolves to a boolean value.
> If we add not unary predicates but unary expressions we could move all the relation & pattern-matching stuff out of `predicate` into `_expression`
Based on …
> Remove predicate and merge into binary_expression

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/create.txt
- test/corpus/cte.txt
- test/corpus/delete.txt
- test/corpus/expressions.txt
- test/corpus/group_by.txt
- test/corpus/index.txt
- test/corpus/insert.txt
- test/corpus/select.txt
- test/corpus/subquery.txt
- test/corpus/transaction.txt
- test/corpus/update.txt
- test/corpus/window_functions.txt
Some more redundancies; feel free to exercise a line item veto here, I've itemized the commits.
I wanted to pull these out because they wrap _expressions at fixed or trivially findable positions in their respective clauses:
- join_expression: after `on`
- where_expression: always second
- order_expression: always third
- expression_list: always third (in partition and group)
- assignment_list: after `set`
- insert_expression: after `into`, basically split inserts in half
on column_list it just felt wrong that the most common use was anonymized and aliased while the somewhat obscure ordered syntax (not actually used in order_by, which has its own thing going on!) got pride of place. I've changed the alias to a more uniform `list`.
> more expression and other cleanup

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/functions.txt
- test/corpus/insert.txt
- test/corpus/transaction.txt
- test/corpus/update.txt
There are 3 updates that fix the issues described in https://github.com/DerekStride/tree-sitter-sql/issues/67.
cc// @LeoniePhiline
https://github.com/DerekStride/tree-sitter-sql/pull/68/commits/3f08080faf4902ce2f528c4ae699fb42169131ae
https://github.com/DerekStride/tree-sitter-sql/pull/68/commits/2fdc42869aafb9d00d28ccaee6be8b10c0386f1b
Also updates the values branch of the grammar to allow for specifying multiple lists of items. The other commit includes support for the postgres style update statement.
https://github.com/DerekStride/tree-sitter-sql/pull/68/commits/8c0ca86319fe745eebfe7d8ebdf6ac43100517ba
https://github.com/DerekStride/tree-sitter-sql/pull/68/commits/61c6e23337ed72464dc5c614fc47f876c1ad6ad6
Previous to this commit `count` was a special case node. It worked a lot like the …
> Various improvements: aggregate functions, insert set syntax, & update join syntax

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/create.txt
Fixes one problem reported in #71
Modified `column_definitions` to accept `DEFAULT` with `literal` or `invocation` optionally in parenthesis.
> Default values in Column Definitions

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/create.txt
I noticed that currently, we cannot parse a statement like:
```sql
CREATE TABLE tab1 AS SELECT * FROM tab2
```
This is now possible. I also added the `ON COMMIT` behavior for temp tables and the `UNLOGGED` options.
Reference: https://www.postgresql.org/docs/15/sql-createtableas.html
> Parse more functionality of the `CREATE TABLE` statement

- README.md
The repository https://github.com/tk-shirasaka/tree-sitter-sql no longer exists.
> Other projects: Remove https://github.com/tk-shirasaka/tree-sitter-sql (was deleted)

- grammar.js
- src/grammar.json
- test/corpus/alter.txt
Fixes #78
I changed `grammar.js`, then ran `tree-sitter generate`. `src/` was updated. 
Did I do that correctly? I haven't worked with tree sitter grammars yet.
I also ran `tree-sitter build-wasm` and `tree-sitter playground` to verify the fix.
> feat: Optional `COLUMN` in `ALTER TABLE` for `ADD`, `CHANGE` and `DROP`

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/create.txt
This PR adds hive specific syntax for `CREATE TABLE` statements following the Impala syntax.
Hive style databases have an even more diverse set of SQL statements. I have tried to integrate them into the current syntax as smooth as possible. I have created a new node called `table_settings` with should include most of the new statements. Some of them are also supported by MySQL and Postgres (e.g. `PARTITION|PARTITIONED BY`). I also modified a bit the `TABLEPROPERTIES` since the `TBLPROPERTIES` of are quite similar.
Here is the reference statement that I tried to implement:
```SQL
CREATE [EXTERNAL] TABLE [IF NOT EXISTS] [db_name.]table_name
(col_name data_type
[constraint_specification]
[COMMENT 'col_comment']
[, ...]
)
[PARTITIONED BY (col_name data_type, ...)]
[SORT BY ([column [, column …
```
> Add Hive statements

- grammar.js
- src/grammar.json
- test/corpus/select.txt
Fixes #81
I have added the regex. Where should the node go?
When I add them to L1573:
```javascript
_expression: $ => prec(1,
choice(
$.literal,
$._decimal_number,
$.field,
$.parameter,
$.list,
$.case,
$.window_function,
$.subquery,
$.cast,
alias($.implicit_cast, $.cast),
$._aggregate_function,
$.invocation,
$.binary_expression,
$.unary_expression,
$.array,
)
),
```
Then a lot of tests fail, because instead of matching on `all_fields` it matches to `binary_expression`. This has probably to do with the `prec()` of this node.
> feat: Parse float

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/casting.txt
- test/corpus/select.txt
Postgres interval parsing like:
`select '1 day'::interval`
or
`SELECT timestamp with time zone '2005-04-02 12:00:00-07' + interval '24 hours'`
> feat(pg): add interval parsing

- grammar.js
- src/grammar.json
- test/corpus/select.txt
This fixes statements like
`select tab."Col" from tab`
In a previous commit we already got the following variations working:
`select "Schem"."Tabl"."CLMN" from "Tabl"`
and
`select "Col" from tab`
Fixes #93
> fix: partially quoted expression

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/alter.txt
Replacing the accidentally merged #98.
This PR is a draft just to show I'm working on that, since now other PRs have been merged and no parser code clashes await.
- https://github.com/DerekStride/tree-sitter-sql/issues/82
- https://github.com/DerekStride/tree-sitter-sql/issues/83
- https://github.com/DerekStride/tree-sitter-sql/issues/89
- #71 
- [fix: Lift `ALTER TABLE` combination restriction (only Postgres)](https://github.com/DerekStride/tree-sitter-sql/commit/be20ed053a6d0a6125e485f4796a488f91df987d)
Resolves comment: https://github.com/DerekStride/tree-sitter-sql/issues/82#issuecomment-1416227381
- [feat: Add MariaDB/MySQL `ALTER TABLE ... CHANGE ...`](https://github.com/DerekStride/tree-sitter-sql/pull/99/commits/1124c5151320e6c1107ef7afc7f61b91690f0ebe)
Fixes: …
> feat: Implement MariaDB `ALTER TABLE` syntax

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/create.txt
Fixes #104 
I am not 100% sure that the resulting AST is correct:
```
(program [0, 0] - [5, 0]
(statement [0, 0] - [3, 1]
(create_table [0, 0] - [3, 1]
(keyword_create [0, 0] - [0, 6])
(keyword_table [0, 7] - [0, 12])
(table_reference [0, 13] - [0, 16]
name: (identifier [0, 13] - [0, 16]))
(keyword_as [0, 17] - [0, 19])
(keyword_with [1, 0] - [1, 4])
(cte [1, 5] - [3, 1]
(identifier [1, 5] - [1, 9])
(keyword_as [1, 10] - [1, 12])
(statement [2, 4] - [2, 19]
(select [2, 4] - [2, 12]
(keyword_select [2, 4] - [2, 10])
(select_expression [2, 11] - [2, 12]
(term [2, 11] - [2, 12]
value: (field [2, 11] - [2, 12]
name: (identifier [2, 11] - [2, 12])))))
(from [2, 13] - [2, 19]
(keyword_from [2, 13] - [2, 17])
(relation [2, 18] - [2, 19]
(table_reference [2, 18] - [2, 19]
name: (identifier [2, …
```
> Create Tables/views from CTE's

- grammar.js
- src/grammar.json
- test/corpus/select.txt
`'foo''bar'` => literal `foo'bar`
- Not sure where the tests should go or if more are needed, but I put them in `select.txt` for now
- Ran `tree-sitter generate --abi 13 && tree-sitter test`, is that it?
> feat: support single quotes in string literals

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/expressions.txt
The parser was not setup to handle `<>` causing an error when trying to parse SQL queries containing it. 
This change simply adds `<>` to the list of valid expressions, and tests it accordingly. 
Note: since <> is a literal string, it isn't considered a `named node` and won't appear in the tests. This is consistent with operators such as `<=`.
> Add NOT `<>` expression to grammar

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/create.txt
This PR extends #107 and includes also the variations for Postgres, MySQL and MariaDB. Thus, merging #107 is not necessary anymore, since there was not feedback in over a week.
> feat: add bit datatype

- grammar.js
- src/grammar.json
- src/node-types.json
- test/corpus/create.txt
Adds datatypes `string` and `binary` for hive.
`char`, `varchar` and `numeric` where specified twice.
> feat: add `binary` and `string` datatypes for hive

- grammar.js
- test/corpus/create.txt
fixes #122 
I am not sure if adding the new keyword `current_timestamp` directly to the option of `_inner_default_expression` is the best way. However it does not fit into one of the others options that are already there.
> feat: add `default_timestamp` option

- grammar.js
- test/corpus/create.txt
`check option` should be an extra node to allow to query it for highlighting
See https://github.com/nvim-treesitter/nvim-treesitter/pull/4541
> fix: `check option` as extra keyword nodes (for better highlighting)

- grammar.js
- test/corpus/functions.txt
- test/corpus/select.txt
There's three changes being made in this PR, each are contained to individual commits.
1. Support for parenthesized expression. e.g. wrapping expressions in `(` & `)` to group them.
2. Support for the [`EXISTS`](https://dev.mysql.com/doc/refman/8.0/en/exists-and-not-exists-subqueries.html) expression.
- Includes subquery support for `IN`
- Excludes `NOT IN`, there was conflicts with precedence that I want to sort out separately.
3. Support for [`ANY`, `SOME`, & `ALL`](https://www.postgresql.org/docs/current/functions-subquery.html)
> Add support for parenthesized expressions & EXISTS subquery

- grammar.js
- test/corpus/create.txt
adds support for the MySQL COMMENT keyword in column definitions: https://dev.mysql.com/doc/refman/8.0/en/create-table.html
> add support for mysql comment keyword in column definition

- grammar.js
- test/corpus/alter.txt
- test/corpus/create.txt
- test/corpus/cte.txt
- test/corpus/insert.txt
- test/corpus/select.txt
fixes #137 
This PR adds fixes for all the parse errors from the file in #137 & https://github.com/nvim-treesitter/nvim-treesitter/issues/4668.
<details>
<summary>Integration test: <code>tree-sitter parse tmp/issue_137.sql</code></summary>
```
➜ tree-sitter-sql tree-sitter parse tmp/issue_137.sql | rg ERROR
➜ tree-sitter-sql tree-sitter parse tmp/issue_137.sql
(program [0, 0] - [63, 0]
(statement [0, 0] - [3, 2]
(create_table [0, 0] - [3, 1]
(keyword_create [0, 0] - [0, 6])
(keyword_table [0, 7] - [0, 12])
(table_reference [0, 13] - [0, 19]
name: (identifier [0, 13] - [0, 19]))
(column_definitions [0, 20] - [3, 1]
(column_definition [1, 2] - [1, 46]
name: (identifier [1, 2] - [1, 10])
type: (bigint [1, 11] - [1, 17]
(keyword_bigint [1, 11] - [1, 17]))
(keyword_generated [1, 18] - [1, 27]) …
```
> fix: various errors

- grammar.js
- test/corpus/window_functions.txt
* adds `count` as an option for the aggregation in window functions
@DerekStride a general question regarding the `count` node. For other functions we have the `invocation`. Why do we have this separation? 
In Impala the count in window function can also be empty (haven't checked other dialects) like:
`count() over (partition by col)`
Do you think we should rethink how we handle `invocations`. Maybe a named node for all possibile functions (`now`, `avg`, `sum`, `date_trunc`... <endless list>)
> allow count in window functions

- grammar.js
- test/corpus/create.txt
- test/corpus/functions.txt
- test/corpus/select.txt
not perfect but it's (Postgres-flavored) progress!
@matthias-Q I ran into a conflict between `create function x () as 'select 1'` and `create table y (id int) 'param'='value'`. Setting left precedence on `create table` worked, and I have a test case with a string-bodied function creating a table with options, although non-quoted since quoting _within_ a quote-delimited functino body isn't there yet. I did reorganize table settings under table options since they seem like roughly the same thing, and added Databricks' explicit `options` while trying to get to the bottom of the conflict.
Otherwise:
- lateral cross joins don't take an `on`, so that's fixed
- I did look into adding a custom scanner for tracking dollar quote opening/closing a while back but didn't have much success. I've …
> feat: create function

- grammar.js
- test/corpus/insert.txt
Closes #147 
Added `insert overwrite` with spark sql like partition configuration.
> feat: add `insert overwrite` from spark sql

- grammar.js
- test/corpus/functions.txt
- test/corpus/select.txt
Closes #154 
Distinct has been misidentified as a field. The pg specific `order by` was not working at all (we had a test for that)
@DerekStride should we add a CI test that checks for `ERROR` in the tests? (excluding error.txt) to avoid this from happening again?
> fix: distinct and order by in invocation

- grammar.js
- test/corpus/alter.txt
- test/corpus/comment.txt
- test/corpus/compound_statements.txt
- test/corpus/create.txt
- test/corpus/cte.txt
- test/corpus/delete.txt
- test/corpus/drop.txt
- test/corpus/expressions.txt
- test/corpus/functions.txt
- test/corpus/group_by.txt
- test/corpus/index.txt
- test/corpus/insert.txt
- test/corpus/select.txt
- test/corpus/subquery.txt
- test/corpus/transaction.txt
- test/corpus/update.txt
- test/corpus/window_functions.txt
Incorporates #149 ; not ready for primetime yet, there are four test failures that mostly stem from incorrect precedence negotiation between `object_reference` and `field` -- give it a whirl if you have time!
@matthias-Q if this is too much (it's a lot) you can avoid a lot of the precedence-setting in #149 by setting it in `parametric_type` as here. It still wants the precedence on `relation` but I haven't gone too far down that rabbit hole yet.
> refactor: consolidate table_reference and invocation identifier into object_reference

- grammar.js
- test/corpus/cte.txt
- test/corpus/select.txt
Addresses a remaining issue in #145 
It works, but I am not so super happy with it. I had to enter alot of associativity rules. Maybe that was necessary, since the change is so high up in the AST and it affects parenthesis.
Also, I am always about creating the anonymous nodes to reduce code replication like in `_cte_select_variants`.
P.S.
For MySQL, this is documented: https://dev.mysql.com/doc/refman/8.0/en/parenthesized-query-expressions.html
> feat: add parenthesized select and cte select statements

- grammar.js
- test/corpus/create.txt
Impala/Hive have different variations of CREATE TABLE. Partitioning has a slightly different style for external and managed tables:
https://impala.apache.org/docs/build/html/topics/impala_create_table.html
For managed tables you do not have to specify the data type of the partition.
Closes #161
> fix: impala partitioning variation

- grammar.js
- queries/indents.scm
- test/corpus/compound_statements.txt
- test/corpus/functions.txt
eliminates the recently added conflicts, shaves a few seconds off compile time, and state count in the parser is cut by over half -- from 7151 states to 3087!
Other changes:
- `compound_statement` has been renamed to `block`
- `create_function` uses `object_reference` correctly
- we've lost parsing of 'string' function bodies but that was probably a bad idea to begin with
> refactor: programs as delimited sequences of statements

- grammar.js
- test/corpus/select.txt
I am not sure if the `filter_expression` should be inside the choice node our outside. Currently, a normal invocation can be followed by the `filter_expression`. (which is probably fine.)
Closes #167
> feat: add `filter` to `aggregate_functions`

- grammar.js
- test/corpus/cte.txt
closes #165
@matthias-Q you were close! `_cte` doesn't work in that position because it doesn't allow for the statement that has to follow the with (....) expression.
> feat: nested common table expressions

- grammar.js
- test/corpus/json.txt
Alternative to #170 that uses the `binary_expression` node.
```
➜ tree-sitter-sql tree-sitter parse tmp/json.sql
(program [0, 0] - [7, 0]
(statement [0, 0] - [6, 10]
(select [0, 0] - [5, 35]
(keyword_select [0, 0] - [0, 6])
(select_expression [1, 4] - [5, 35]
(term [1, 4] - [1, 29]
value: (binary_expression [1, 4] - [1, 20]
left: (literal [1, 4] - [1, 10])
right: (literal [1, 13] - [1, 20]))
(keyword_as [1, 21] - [1, 23])
alias: (identifier [1, 24] - [1, 29]))
(term [2, 4] - [2, 32]
value: (binary_expression [2, 4] - [2, 32]
left: (binary_expression [2, 4] - [2, 21]
left: (literal [2, 4] - [2, 10])
right: (literal [2, 12] - [2, 21]))
right: (literal [2, 26] - [2, 32])))
(term [3, 4] - [3, 46]
value: (binary_expression [3, 4] - [3, 33]
left: (binary_expression [3, 4] - [3, 21]
left: …
```
> alternative implementation using binary_expression

- grammar.js
- test/corpus/alter.txt
Closes #135 and supersedes #144
I feel this is a bit hacky, but I just made the `add` keyword optional, so that it will not repeated in `_alter_specifications`
I also removed that `rename` part of the test, since this is not valid SQL syntax and made the keyword `constrain` optional. See discussion in #144
> feat: tsql multiple add columns in alter statement

- .github/workflows/gh-pages.yml
Alternative to https://github.com/DerekStride/tree-sitter-sql/pull/172
This allows swift & other projects that depend on the `bindings/` being present to function without generating them from the `main` branch.
cc// @bombardier200 @mattmassicotte
> Add bindings & Package.swift to gh-pages build

- grammar.js
- queries/highlights.scm
- test/corpus/create.txt
- test/corpus/cte.txt
- test/corpus/select.txt
- test/highlight/union.sql
fixes https://github.com/DerekStride/tree-sitter-sql/issues/176
Commits might be easier to review separately
* New `optional_parenthesis` & `wrapped_in_parenthesis` functions to make it easier work with parenthesis
* Alias custom `create_query` node with `_dml_read`
* New ~`union` & `intersection`~ `set_operation` node instead of having custom rules in `_select_statement`
> Update unions with named node & allow more optional paranthesis

- grammar.js
- test/corpus/create.txt
> feat(pg): create columns as array and matrices

- grammar.js
- test/corpus/cte.txt
This add recursive CTEs.
I was thinking about an alternative implementation. Instead of
```
cte: $ => seq(
$.identifier,
optional(paren_list(field("argument", $.identifier))),
$.keyword_as,
...
```
we could use 
```
cte: $ => seq(
choice(
$.identifier,
$.invocation
),
$.keyword_as,
...
```
But `invocation` would be more permissive and is technically wrong.
> feat: add recursive cte

- grammar.js
- queries/highlights.scm
- test/corpus/create.txt
Fixes #193
Unfortunately, it needs a left precedence to work.
There was also another test condition that was wrong since the last release.
> Allow expr in `generated always` statement

- grammar.js
- test/corpus/alter.txt
- test/corpus/create.txt
Make the statement work with postgres syntax while keeping the previous mariadb syntax (which seems to be used in create table only).
Why does `ALTER TABLE "Role" ADD CONSTRAINT "pkRole" PRIMARY KEY ("roleId");` CST has `ordered_columns` while
`ALTER TABLE table_name ADD CONSTRAINT constraint_name UNIQUE (col1, col2, col3);` does not ?
> Fix ALTER TABLE ... ADD CONSTRAINT ... UNIQUE

- grammar.js
- queries/highlights.scm
Fixes CI build fail due to duplicated keyword in highlights.scm and gammar.js
Introduced in #207
I do not quite understand why CI checks where green on the PR and are failing after landing the PR.
> fix: remove duplicated keyword

- Package.swift
- README.md
Prior to this change, a new scanner.c source file had been added to the repository. The Makefile had been updated, but the command in the README was missing the new file.
This change adds the new file to the command in the README, and also updates the Package.swift file to declare it as a source.
I think this PR is just a bugfix following from #203.
> Add missing scanner.c to README and Package.swift

- queries/highlights.scm
* use `match` instead of `lua-match`
Addresses #220
> fix: replace `lua-match` with `match` in highlights.scm

- .gitattributes
- .github/workflows/ci.yml
- .github/workflows/gh-pages.yml
- package-lock.json
- package.json
In #100 we removed the generated files an publish them via GitHub pages. Since then we've added a custom src/scanner.c file that is being treated as a generated file on GitHub due to the .gitattributes file. Since it's no longer needed, I've removing it.
> Remove gitattributes

- grammar.js
- test/corpus/create.txt
- test/corpus/index.txt
See [postgresql CREATE INDEX docs](https://www.postgresql.org/docs/current/sql-createindex.html)
The CREATE INDEX statement should be able to support three different types of index fields:
1. Column names
2. Expressions (wrapped in parentheses)
3. Function calls
This PR adds those features to the CREATE INDEX statement while preserving backwards compatibility with existing tests/queries. 
There is some code duplication going on here that I couldn't figure out how to resolve; maybe someone has a suggestion for how this can be improved. Each of the three types of index fields takes a set of optional parameters, but I couldn't break them out into their own rule since they are all optional and a rule containing only optional fields would match the empty string rule and therefore be invalid. I …
> feat!: Add complex index fields to CREATE INDEX statements

- grammar.js
- test/corpus/expressions.txt
closes #213
Adds new subscript node to expression. I had to update some precedence rules to avoid conflicts, review ignoring whitespace to easily see the diffs related to that change.
ref: https://www.postgresql.org/docs/current/sql-expressions.html#SQL-EXPRESSIONS-SUBSCRIPTS
> feat: postgresql expression subscripts

- .gitignore
- README.md
fixes #231 
> I'm not well versed on the npm publish behavior, but I think this is being caused by [having /src/ defined on .gitignore](https://github.com/DerekStride/tree-sitter-sql/blob/a65f58c364f4051e14c54be06dfdb91b546d6e7f/.gitignore#L12).
[This was the issue](https://docs.npmjs.com/cli/v10/using-npm/developers#keeping-files-out-of-your-package) and updating the `.gitignore` to be more specific solved the issue.
```
$ npm pack --dry-run 2>&1 | rg src
npm notice 4.8kB  src/scanner.c
```
> fix: ensure scanner.c is included in npm package

- CHANGELOG.md
- CONTRIBUTING.md
- package.json
Follow-up to https://github.com/DerekStride/tree-sitter-sql/pull/232 which will trigger a new release to fix the broken package on npm.
The github release feature allows tagging the release when it's created, I've updated our `commit-and-tag-version` plugin to avoid tagging the commit & updated the docs.
> chore(release): v0.2.0

- src/scanner.c
- test/corpus/errors.txt
Whitespace characters not allowed in dollar quoted tags.
[docs](https://www.postgresql.org/docs/16/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING):
> The tag, if any, of a dollar-quoted string follows the same rules as an unquoted identifier, except that it cannot contain a dollar sign.
Fixes problems with [sqlc](https://github.com/sqlc-dev/sqlc) queries, which use positional parameters outside function definitions or prepared statements. For example:
```sql
SELECT * FROM a
LIMIT $1 OFFSET $2;
SELECT * FROM b
LIMIT $1 OFFSET $2;
```
`$1 OFFSET $` should not be recognized as a tag name.
> fix(scanner): do not allow whitespaces in dollar quote tag

- .github/workflows/gh-pages.yml
> add: Cargo.toml in release

- grammar.js
- test/corpus/create.txt
fixes #247 
@DerekStride I think I have a newer version of tree-sitter on my machine and I get a bunch of warnings. There was a change about the order of query matches (which breaks the tests) and something related to non static functions in the scanner.c
> add: `check constraint` for column definitions

- grammar.js
- test/corpus/create.txt
This is an attempt to solve #249 . 
I updated a test to include the UNIQUE keyword. However, I'm having trouble running the tests (even before making these changes) to verify if everything is correct:
```
$ make test
test
make: *** [Makefile:26: test] Error 1
```
EDIT: found how to run the tests. There is one that is failing (but already was failing before I believe). 
Maybe the [tree-sitter-cli](https://github.com/tree-sitter/tree-sitter/blob/master/cli) requirement should be mentioned in [CONTRIBUTING.md](https://github.com/DerekStride/tree-sitter-sql/blob/main/CONTRIBUTING.md)?
Please let me know if there is something else that I should do/change!
> fix: add unique constraint

- Cargo.toml
Hi ast-grep author here. To use tree-sitter-sql with a newer tree-sitter library, the cargo.toml can be updated. 
I'm using the tree-sitter-javascript as a reference.
https://github.com/tree-sitter/tree-sitter-javascript/blob/master/Cargo.toml
Hope this can help a new release of tree-sitter-sql!
> chore: use newer tree-sitter version

- .github/workflows/publish.yml
- Cargo.toml
- README.md
I hand published this project under the crate name [tree-sitter-sequel](https://crates.io/crates/tree-sitter-sequel) since `tree-sitter-sql` was already taken.
This PR updates the cargo.toml manifest to reflect the published name & sets up a workflow to automatically publish new versions on release.
cc// @HerringtonDarkholme @alexbit-codemod
> chore: update crate name to avoid conflicts

- .github/workflows/publish.yml
The cargo publish workflow failed because the parser files weren't present. By running `npm ci` we force the files to be generated and ensure the test suite passes before publishing the crate.
https://github.com/DerekStride/tree-sitter-sql/actions/runs/10167937438/job/28121386966
In the meantime I've published v0.3.3 manually: https://crates.io/crates/tree-sitter-sequel
> fix(ci): generate the parser artifacts before cargo publish

- .github/workflows/publish.yml
Publish package to pypi, part of #269. I'm testing out the [tree-sitter/workflows](https://github.com/tree-sitter/workflows), if it works without the generated parser files being present we can try migrating the other workflows.
> feat: publish package to pypi

- .github/workflows/publish.yml
- setup.py
The cargo & python publish steps didn't work. The cargo step was simple to fix just requiring a `--allow-dirty` flag to be passed to the action.
The python workflow requires a bit of extra work, I've opened a PR on the main workflow repo and changed this repo to reference my branch: https://github.com/tree-sitter/workflows/pull/14
> Publish fixes

- grammar.js
- test/corpus/create.txt
- test/corpus/expressions.txt
- test/corpus/functions.txt
- test/corpus/merge.txt
- test/corpus/select.txt
Addresses #274
adds a node for `parenthesized_expressions` to improve query QoL.
Remark. I am not sure about the precedence between `list` and `parenthesized_expression`. Please take a close look at the tests. There are some changes, which might be cause by this change, formatting or the precedence. They may make the result AST nonsensical.
> add: `parenthesized_expression`

- grammar.js
- test/corpus/alter.txt
I don't know many sql dialects but such syntax is at least supported by postgresql: 
https://www.postgresql.org/docs/17/sql-altertable.html
> DROP CONSTRAINT [ IF EXISTS ]  constraint_name [ RESTRICT | CASCADE ]
Here's a little visual change:
> feat: drop constraint rule

- grammar.js
- queries/highlights.scm
- test/corpus/insert.txt
Adds support for [`ON DUPLICATE KEY UPDATE `](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html). Ref: [Grammar Definition](https://dev.mysql.com/doc/refman/8.0/en/insert.html).
> feat: ON DUPLICATE KEY UPDATE

- CMakeLists.txt
- Cargo.toml
- Package.swift
- bindings/c/tree-sitter-sql.pc.in
- bindings/go/binding_test.go
- bindings/node/binding.cc
- bindings/python/tree_sitter_sql/__init__.py
- bindings/python/tree_sitter_sql/__init__.pyi
- bindings/rust/build.rs
- bindings/rust/lib.rs
- package-lock.json
- package.json
- pyproject.toml
- tree-sitter.json
needs #279 
changes required to upgrade to tree-sitter 0.24. But it looks like there is at least one issue with a 0.24 upgrade (#282), and upgrading to 0.23 has the advantage of moving Rust bindings to `tree-sitter-language` and simplifying further upgrades there.
> tree-sitter 0.24 upgrade

- grammar.js
- queries/highlights.scm
- test/corpus/select.txt
Closes #284 
I am not so sure about the alias at the end. 
`relation` can already have an alias, but it does not support this unpacking of arrays. So this compiles, but the resulting AST might be misleading-
> feat: add `cross join unnest with ordinality`

- CMakeLists.txt
- CONTRIBUTING.md
- Cargo.toml
- pyproject.toml
- tree-sitter.json
I forgot that we need to manually update the version numbers for some of the other dependencies. I added a mention of it to the CONTRIBUTING.md docs so we don't forget again.
> fix: bump other versions to 0.3.6 and add to docs

- .github/workflows/gh-pages.yml
closes #295
Adds the CMakeLists.txt to the files copied to the gh-pages branch.
cc @toge
> build: add CMakeLists.txt to gh-pages build

- grammar.js
- test/corpus/literals.txt
Adds missing `\` to escape the `\` for strings containing `\'`.
> fix: termination of Postgres escape strings

- CHANGELOG.md
- CMakeLists.txt
- Cargo.toml
- package-lock.json
- package.json
- pyproject.toml
- tree-sitter.json
I had to pin `tree-sitter-cli` to `v0.24.7` in the `npx --package` command because the node bindings [vendor an older version of tree-sitter](https://github.com/tree-sitter/node-tree-sitter/tree/master/vendor). The `v0.25.x` versions are relatively new.
> chore(release): 0.3.8

- bindings/go/binding_test.go
Fix the module path in binding_test.go to fix issues that occur when installing the bindings from golang this addresses #308
> fix: module path in binding_test.go

- grammar.js
- test/corpus/alter.txt
- test/corpus/comment_stat.txt
- test/corpus/create.txt
- test/corpus/delete.txt
- test/corpus/drop.txt
- test/corpus/select.txt
Add optional database name to the object_reference rule and add some tests to add the new functionality
> fix(ast): Add database name to object_reference
